apiVersion: v1
kind: Service
metadata:
  name: dataweb1
  labels:
    name: dataweb
    app: demo
spec:
  selector:
    name: dataweb 
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 5001
     nodePort: 30046
     protocol: TCP